### ISSUE TITLE
Tri 3 TT0

### ISSUE THREAD

**Issue by avabrooks** [avabrooks/avarepository#1]
Scrum Team GitHub pages (2 points)

- Project pages
  - [Web Project: ](https://unblocked00.github.io/swagketo/web)Project Description, Ideas, Wires, Success idea
- [Team Roles](https://unblocked00.github.io/swagketo/) described, Project Owner described, [Scrum Board](https://github.com/avabrooks/swagketo/projects/1) started

Individual GitHub pages (3 points):
- Navigates notes and plans for each [Tech Talk](https://avabrooks.github.io/avarepository/techtalks)
- Contains Test Prep plans and participation for success on AP exam (required for test takers) - not taking AP test
- Navigates to Data Structures work, contains [code snippets](https://avabrooks.github.io/avarepository/techtalks) on problems solutions, links to GitHub for Code, Replit for runtime, or alternatives

**Comment by 4disease** [comment]
## Team 
- Project pages: 1/1 Good brainstorming of project, wireframes, provides references for code later
- Roles: 1/1 Roles described, project owner, scrum board is organized
## Individual
- Tech talk: 1/1.5 Minimal notes about tech talk material, could be more in-depth
- Data Structures work: 1.5/1.5 Working runtime of hacks and good annotation of code snippets
