### ISSUE TITLE
Data Structures Challenge 1: 4.7/5

### ISSUE THREAD

**Issue by avabrooks** [avabrooks/avarepository#2]
[Individual GitHub pages](https://avabrooks.github.io/avarepository/) (4 points)

- GitHub [review page](https://avabrooks.github.io/avarepository/techtalks) that documents key learnings using code snippets
- GitHub [review page](https://avabrooks.github.io/avarepository/techtalks),  [Replit ](https://replit.com/@avabrooks/Tri-3-TT0#src/Menu.java)for runtime to TT1 Challenges.
  - Describe Linked Lists, Describe Java Generic T
  - [Queue Add and Delete](https://replit.com/@avabrooks/Tri-3-TT0#src/MyQueue.java)
  - [Merge ](https://replit.com/@avabrooks/Tri-3-TT0#src/MergeQueue.java)2 Queues
  - Build [Stack](https://replit.com/@avabrooks/Tri-3-TT0#src/MyStack.java) and reverse Queue Order

**Grader: Ridhima**

**Comment by ridhimainukurti** [comment]
Indi Score: (12/12 checks = 4/4 points) + 0.9/1

1/1- One check, both are described in notes
       Queue Add and Delete [review pages + notes](https://avabrooks.github.io/avarepository/techtalks)
1/1 - One check for comments [comments](https://replit.com/@avabrooks/Tri-3-TT0#src/MyQueue.java)
1/1 - One check for Add, running example [add example](https://replit.com/@avabrooks/Tri-3-TT0#src/MyQueue.java)
2/2 - Two checks for Delete, one for individual implementation of Delete and one for running example [delete example](https://replit.com/@avabrooks/Tri-3-TT0#src/MyQueue.java)

Merge 2 Queues 
1/1 - One check for comments 
2/2 - Two checks, one for individual implementation of Merge method(s) and one for running example

Build Stack and reverse Queue Order
2/2 - Two checks, class definition
1/1 - One check, comments and general purpose tester
1/1 - One check, reverse order test case from Queue to Stack
