### ISSUE TITLE
Score: 5/5 Grader: Natasha; Data Structure Challenge #2(Ava)

### ISSUE THREAD

**Issue by avabrooks** [avabrooks/avarepository#3]
Individual GitHub pages (2 points)

- GitHub [review page](https://avabrooks.github.io/avarepository/techtalks) that documents key learnings using code snippets
- [Calculator Code](https://replit.com/@avabrooks/Tri-3-TT0#src/Calculator.java) 

Team score: 3/3
Individual Score: 2/2
Graded by: Natasha

**Comment by mistylavender** [comment]
Total Score: 5/5

Individual: 2/2 
- has a review page with the different parts of the code described and typed out for the plan as well as the general notes for rpn method
- all functions of calculator works including parenthesis and power
- no extra credit taken part in
