### ISSUE TITLE
Grade: 4.75/5 | Grader: Adi | Sorts and Analysis

### ISSUE THREAD

**Issue by avabrooks** [avabrooks/avarepository#4]
**[Sorts ](https://replit.com/@avabrooks/Tri-3-TT#src/Sorts.java)and Analysis -- Coding, Comments, and Documentation:**

- [Build](https://replit.com/@avabrooks/Tri-3-TT#src/Sorts.java) custom Bubble Sort, Selection Sort, Insertion Sort and Merge Sort. 25%
- Build a GitHub [page ](https://avabrooks.github.io/avarepository/TTW3)that describes Sort implementations and the Big O complexity of these Sorts. 25%
- [Analysis ](https://avabrooks.github.io/avarepository/TTW3) 25%
- Establish [analytics ](https://replit.com/@avabrooks/Tri-3-TT#src/Sorts.java)including: time, comparisons and swaps.
- [Average ](https://replit.com/@avabrooks/Tri-3-TT#src/Sorts.java)the results for each each Sort, run each at least 12 times and 5000 elements
- Make your [final/judgment](https://avabrooks.github.io/avarepository/TTW3) on best sort considering Data Structure loading, Comparisons, Swaps, Big O complexity, and Time.

**Individual GitHub pages, Replit, IntelliJ 25%:**

- Organize files, directories and [menus](https://replit.com/@avabrooks/Tri-3-TT) for all weeks.
- Make your GitHub pages fold into a [personal portfolio](https://github.com/avabrooks/avarepository/tree/gh-pages)
- Make sure all Code and Analytics runs on [Replit ](https://replit.com/@avabrooks/Tri-3-TT#src/Sorts.java)and [IntelliJ](https://github.com/avabrooks/avarepository)
- Ensure Individual GitHub Repository shows iteration on work (minimum of 10 commits on [Java [](](https://github.com/avabrooks/avarepository/commits/main)and) 10 commits on [Pages](https://github.com/avabrooks/avarepository/commits/gh-pages)

**Comment by adhithin** [comment]
Sorts and Analysis -- Coding, Comments, and Documentation:

- [ ] [Build](https://replit.com/@avabrooks/Tri-3-TT#src/Sorts.java) custom Bubble Sort, Selection Sort, Insertion Sort and Merge Sort. 25% 

- [ ] Build a GitHub [page ](https://avabrooks.github.io/avarepository/TTW3)that describes Sort implementations and the Big O complexity of these Sorts. 25%
- [ ] [Analysis ](https://avabrooks.github.io/avarepository/TTW3)25%
- [ ] Establish [analytics ](https://replit.com/@avabrooks/Tri-3-TT#src/Sorts.java)including: time, comparisons and swaps
- [ ] [Average ](https://replit.com/@avabrooks/Tri-3-TT#src/Sorts.java)the results for each each Sort, run each at least 12 times and 5000 elements
- [ ] Make your [final/judgment](https://avabrooks.github.io/avarepository/TTW3) on best sort considering Data Structure loading, Comparisons, Swaps, Big O complexity, and Time.
- [ ] Individual GitHub pages, Replit, IntelliJ 25%:

- [ ] Organize files, directories and [menus](https://replit.com/@avabrooks/Tri-3-TT) for all weeks.
- [ ] Make your GitHub pages fold into a [personal portfolio](https://github.com/avabrooks/avarepository/tree/gh-pages)
- [ ] Make sure all Code and Analytics runs on [Replit ](https://replit.com/@avabrooks/Tri-3-TT#src/Sorts.java)and [IntelliJ](https://github.com/avabrooks/avarepository)
- [ ] Ensure Individual GitHub Repository shows iteration on work (minimum of 10 commits on [Java 10 commits on [Pages](https://github.com/avabrooks/avarepository/commits/gh-pages))
